### PR TITLE
Return of the vampires of futures past...

### PR DESCRIPTION
**Pull request by Ms-Mee**
## About The Pull Request
This PR adds the vampire quirk in it's unupdated but functional state, alongside the Draculine bloodtype. If there's any issue I missed feel free to SCREAM at me :blush:

## Why It's Good For The Game
The vampire species is rather buggy like the other unmaintaned species and it's hard to use vampires as-is, this also reducing the need for admins to deal with the vampire species change problems (loss of quirks, baldness, loss of hair color). As of course there are characters that are vampires, and it's cool.

## Why Echo, not Shiptest?
The vampire quirk will take a while to be fully remade, and it's messy to have it testmerged and constantly rebalanced on main as it was, especially with the neutral quirk value, still I understand if this PR gets closed.

## Changelog

:cl:
add: Added the Vampire quirk and the Draculine bloodtype.
code: Added the NOHEART species trait for specific applications where one should still bleed and survive without a heart.
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
Also to clarify, not tested yet but it should work, I'll only be able to test it in a few hours

**Comment by Ms-Mee** [comment]
Suddenly, enough free time to redo some things alongside testing this, how fortunate

**Comment by Ms-Mee** [comment]
Could also replace dusting with getting a cursed heart and after a while just dropping dead if they don't get enough blood, I could make a few changes overall, but dusting kinda sucks

**Comment by PrefabQuasar** [comment]
husking would probably be a workable alternative to dusting, and not too hard to implement as changelings already have most of what you'd need to do it

**Comment by Ms-Mee** [comment]
We'll see what madness comes of it, I'm doing evil things as we speak

**Comment by Ms-Mee** [comment]
### Changes made:
Drain blood action (20 units at a time, takes 3 seconds, self-repeating)
Transfer blood action (5 units at a time, also takes 2 seconds, does not self repeat)
Constant bloodloss of 0.2 units per life cycle (0.7 when below the blood level treshold that causes random fainting, unless your heart is a cursed heart, which is not automatically given), possibly too high though I'd need to play an actual round to really know.
Killed, husked and blood volume set to 0 when blood goes below the survival treshold, effectively the same as when drained by a changeling, as it just calls the Drain() proc changelings use.
Vampires no longer need a heart.

Unless there's a request for changes, oversight I really did not notice or rebalancing change absolutely needed, this should be final until I make actual vampirism which won't quite even use quirks, ideally.

**Comment by Vexylius** [comment]
I'm not all convinced if this is a good idea, but if you're willing to fix any bugs that come up and adress feedback, I'll merge it

**Comment by Ms-Mee** [comment]
That is the implicit social contract I abide to when making contributions, indeed

**Comment by Ms-Mee** [comment]
Most easy to find bugs and problems should be addressed by now given the quirk's been tmed on main before and I haven't changed anything big, alongside testing the few things I did change, the main concern as far as problems go is balance, or the lack thereof with the species on which the quirk is based alongside the concept in itself as far as what I can reasonably implement with quirks goes

**Comment by terg-but-ius** [comment]
If it doesn't already, you should probably pull an RDS and make it clear that this quirk isn't an excuse to be outright antagonistic. Ofc conflict may naturally arise but be less Dracula, more uhh...I can't think of a sympathetic popular vampire but you get the gist.

**Comment by Ms-Mee** [comment]
The little vampires from the books, clearly
I suppose I may add it in a bit

**Comment by Ms-Mee** [comment]
image
There ya go

**Comment by Ms-Mee** [comment]
:transgender_flag:

**Pull request merged**
